name: Build Native Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies & Sync Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap sync android

      - name: Build Android App (Assemble Debug)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FoodCourtPOS-Native-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
